"""gen2 integration gates (encoder refactor plan W1 + W2; build spec WP-A test home 2).

Repo-level home per the 2026-07-12 architecture ruling: this test sits ABOVE both skills
and may import both tools; gen2 itself never imports vap2.

W1 gate — emitter equivalence: for each committed fixture, run the OLD generator
(vap_generator.py, subprocess) on the simple-format JSON, decode its XML with vap2, feed
the decoded schema JSON to gen2's emitter, and assert per-action XML equivalence: the
CommandAction subtrees must be byte-identical modulo GUIDs (profile/command/action <Id>s
are freshly generated by design). Generated .vap artifacts go to a tempdir, never the
repo (fixture policy, plan W0b).

W2 gate — schema input: every reference profile's decode loads clean through
schema_input, with unknown markers and unrepresentable types routed to the contract §3
refusal path — counted, never errors. Reference profiles are local-only assets, so each
is guarded skip-if-missing (same require() idiom as test_vap2.py).

Run:  python3 -m unittest discover -s tests/integration -t . -v
"""

import glob
import os
import re
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "skills", "voiceattack-decoder", "scripts"))
sys.path.insert(0, os.path.join(ROOT, "skills", "voiceattack-generator", "scripts"))

import vap2  # noqa: E402
from gen2 import names, schema_input  # noqa: E402
from gen2.emit_profile import emit, route_actions  # noqa: E402

DICT = names.load()  # gen2's own loader; vap2 loads its own dictionary internally
OLD_GENERATOR = os.path.join(ROOT, "skills", "voiceattack-generator", "scripts",
                             "vap_generator.py")
PROFILES = os.path.join(ROOT, "reference profiles")

# Committed simple-format fixtures (plan W0b) the old generator emits cleanly.
W1_FIXTURES = [
    os.path.join(ROOT, "output files", "zoom_zoom.json"),
    os.path.join(ROOT, "cities_skylines_2_conditional.json"),
]

GUID_RE = re.compile(r"<Id>[0-9a-f\-]{36}</Id>")
CHUNK_RE = re.compile(r"<CommandAction>.*?</CommandAction>", re.S)


def mask(chunk):
    return GUID_RE.sub("<Id>GUID</Id>", chunk)


def chunks_of(xml):
    return [mask(c) for c in CHUNK_RE.findall(xml)]


def require(path):
    if not os.path.exists(path):
        raise unittest.SkipTest("missing local asset: %s" % os.path.basename(path))


class W1EmitterEquivalenceTest(unittest.TestCase):
    """Fed schema-JSON records equivalent to the old generator's internal state (its own
    output, decoded), gen2 reproduces the old emitter's per-action XML exactly."""

    def assert_equivalent(self, fixture):
        require(fixture)
        with tempfile.TemporaryDirectory() as td:
            out_vap = os.path.join(td, "old.vap")
            r = subprocess.run(
                [sys.executable, OLD_GENERATOR, fixture, out_vap],
                capture_output=True, text=True)
            self.assertEqual(r.returncode, 0,
                             "old generator failed on %s: %s" % (fixture, r.stderr))
            with open(out_vap, "r", encoding="utf-8") as f:
                old_xml = f.read()
            profile = vap2.decode_file(out_vap)

        model = schema_input.parse(profile)
        new_xml, warnings = emit(model, DICT)
        self.assertEqual(warnings, [],
                         "fixture is fully representable; refusals are a regression")

        old_chunks = chunks_of(old_xml)
        new_chunks = chunks_of(new_xml)
        self.assertEqual(len(old_chunks), len(new_chunks))
        for i, (old, new) in enumerate(zip(old_chunks, new_chunks)):
            self.assertEqual(old, new, "CommandAction %d differs" % i)
        # Command count and phrases survive too (envelope sanity, not the gate proper).
        self.assertEqual(old_xml.count("<Command>"), new_xml.count("<Command>"))
        self.assertEqual(re.findall(r"<CommandString>.*?</CommandString>", old_xml),
                         re.findall(r"<CommandString>.*?</CommandString>", new_xml))

    def test_zoom_zoom(self):
        self.assert_equivalent(W1_FIXTURES[0])

    def test_cities_skylines_2_conditional(self):
        self.assert_equivalent(W1_FIXTURES[1])


class W2SchemaInputTest(unittest.TestCase):
    """Every reference profile's decode loads clean through schema_input; unknown
    markers and unrepresentable types route to counted refusals, not errors."""

    def test_all_reference_profiles_load_clean(self):
        paths = sorted(glob.glob(os.path.join(PROFILES, "*.vap")))
        if not paths:
            self.skipTest("no local reference profiles")
        for path in paths:
            fname = os.path.basename(path)
            with self.subTest(profile=fname):
                profile = vap2.decode_file(path)
                model = schema_input.parse(profile)  # must not raise
                self.assertEqual(len(model["commands"]),
                                 profile["profile"]["commandCount"])

                # Refusal routing: never an exception; every unknown marker in the
                # decode is accounted for by a whole-command refusal warning.
                refusals = []
                unknown_markers = 0
                refused_cmds = 0
                for cmd in model["commands"]:
                    unknown_markers += sum(
                        1 for a in cmd["actions"] if a.get("decoded") is False)
                    if route_actions(cmd, DICT, refusals.append) is None:
                        refused_cmds += 1
                # Routing stops at a command's FIRST unknown marker, so warnings are
                # per-command, bounded by the marker count — and never zero when any
                # marker exists (loud, contract §3).
                unknown_refusals = sum(1 for w in refusals if "unknown marker" in w)
                if unknown_markers == 0:
                    self.assertEqual(unknown_refusals, 0)
                else:
                    self.assertGreaterEqual(unknown_refusals, 1,
                                            "unknown markers must be refused loudly")
                    self.assertLessEqual(unknown_refusals, unknown_markers)
                self.assertLessEqual(refused_cmds, len(model["commands"]))

    def test_reference_profiles_emit_without_hard_fail(self):
        """Beyond the gate: full emission over every reference profile must complete
        (refusals as warnings), proving the refusal routing protects the hard-fail
        validator from unrepresentable real-world input."""
        paths = sorted(glob.glob(os.path.join(PROFILES, "*.vap")))
        if not paths:
            self.skipTest("no local reference profiles")
        for path in paths:
            with self.subTest(profile=os.path.basename(path)):
                model = schema_input.parse(vap2.decode_file(path))
                xml, warnings = emit(model, DICT)  # must not raise EmitError
                self.assertTrue(xml.startswith("<?xml"))


if __name__ == "__main__":
    unittest.main(verbosity=2)
